name: Perform-heartbeat-requests

on:
  schedule:
    - cron: "0 */1 * * *"

env:
  RENDER_PERSONA: ${{ secrets.RENDER_PERSONA }}
  RENDER_MARKUAPI: ${{ secrets.RENDER_MARKUAPI }}
  VERCEL_KURYANA: ${{ secrets.VERCEL_KURYANA }}

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Perform hourly heartbeat for 'persona'
        run: |
            req=$(curl -s $RENDER_PERSONA)
            echo "$req"
            
      - name: Perform hourly heartbeat for 'markuapi'
        run: |
            req=$(curl -s $RENDER_MARKUAPI)
            echo "$req"

      - name: Perform hourly heartbeat for 'kuryana'
        run: |
            req=$(curl -s $VERCEL_KURYANA)
            echo "$req"
