name: Perform-heartbeat-requests

on:
  schedule:
    - cron: "*/15 * * * *" # runs every 15th minute

env:
  RENDER_MARKUAPIZ: ${{ secrets.RENDER_MARKUAPIZ }}
  RENDER_PERSONA: ${{ secrets.RENDER_PERSONA }}

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Perform heartbeat for 'markuapiz'
        if: always()
        run: |
            resp=$(curl -sw '\n%{http_code}' $RENDER_MARKUAPIZ)
            resp_body=$(echo "$resp" | head -n 1)
            resp_code=$(echo "$resp" | tail -n 1)
            
            echo "$resp_body"
            echo "$resp_code"
            
            if [[ "$resp_code" -ne 200 ]]; then
                exit 1
            fi

      - name: Perform heartbeat for 'persona'
        if: always()
        run: |
            resp=$(curl -sw '\n%{http_code}' $RENDER_PERSONA)
            resp_body=$(echo "$resp" | head -n 1)
            resp_code=$(echo "$resp" | tail -n 1)
            
            echo "$resp_body"
            echo "$resp_code"
            
            if [[ "$resp_code" -ne 200 ]]; then
                exit 1
            fi