name: Perform-heartbeat-requests

on:
  schedule:
    - cron: "*/15 * * * *" # runs every 15th minute

env:
  RENDER_MARKUAPIZ: ${{ secrets.RENDER_MARKUAPIZ }}
  RENDER_PERSONA: ${{ secrets.RENDER_PERSONA }}

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Perform heartbeat for 'markuapiz'
        run: |
            req=$(curl -s $RENDER_MARKUAPIZ)
            echo "$req"

      - name: Perform heartbeat for 'persona'
        run: |
            req=$(curl -s $RENDER_PERSONA)
            echo "$req"